name: Build and Slim Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-slim:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
        id-token: write

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        REPO_OWNER=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 1 | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
        echo "REPO_OWNER=${REPO_OWNER}" >> $GITHUB_ENV
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/Groups:latest .

    # Step 4: Slim the Docker image using Kitabisa Action
    - name: Slim Docker image
      uses: kitabisa/docker-slim-action@v1
      env:
        DSLIM_HTTP_PROBE: "false"  # Disables HTTP probing during slimming
      with:
        target: ghcr.io/${{ github.repository_owner }}/Groups:latest # Target image to slim
        tag: slim  # Suffix for the slimmed image tag

    # Step 5: Push the slimmed image to GitHub Container Registry.
    - name: Push slimmed Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/Groups:slim